<?php

$link = 'https://sistemas.pc.sc.gov.br/cidadao/alvaras/Alvara_anual_para_fabricacao_e_comercio_de_fogos_de_artificio_TESTE__fabricao_e_comrcio_de-1702665269.pdf';

include "phpqrcode/qrlib.php";

//QRcode::png('PHP QR Code :)', 'phpqrcode/test.png', 'L', 4, 2);

//include only that one, rest required files will be included from it
//include "qrlib.php";

//write code into file, Error corection lecer is lowest, L (one form: L,M,Q,H)
//each code square will be 4x4 pixels (4x zoom)
//code will have 2 code squares white boundary around 

QRcode::png($link, 'phpqrcode/pngs/test2.png', 'L', 4, 2);

//same as above but outputs file directly into browser (with appr. header etc.)
//all other settings are default
//WARNING! it should be FIRST and ONLY output generated by script, otherwise
//rest of output will land inside PNG binary, breaking it for sure
//QRcode::png($link);

//show benchmark
//QRtools::timeBenchmark();

//rebuild cache
//QRtools::buildCache();

//code generated in text mode - as a binary table
//then displayed out as HTML using Unicode block building chars :)
//$tab = $qr->encode('PHP QR Code :)');
//QRspec::debug($tab, true);

// == TCPDF INTEGRATION ==

// Inside bindings/tcpdf you will find slightly modified 2dbarcodes.php.
// Instal phpqrcode liblaty inside tcpdf folder, then overwrite (or merge)
// 2dbarcodes.php 

// Then use similar as example #50 from TCPDF examples:

// <?php

// $style = array(
//     'border' => true,
//     'padding' => 4,
//     'fgcolor' => array(0,0,0),
//     'bgcolor' => false, //array(255,255,255)
// );

// //code name: QR, specify error correction level after semicolon (L,M,Q,H)
// $pdf->write2DBarcode('PHP QR Code :)', 'QR,L', '', '', 30, 30, $style, 'N');
?>